apiVersion: v1
kind: Pod
metadata:
  name: db-noticias
  labels:
    app: db-noticias
spec:
  containers:
    - name: db-noticias-container
      image: aluracursos/mysql-db:1
      ports:
        - containerPort: 3306
      #env: #Lista de veriaveis de ambiente Estao aqui so para mostrar que pode ser feito assim tambem
        #- name: "MYSQL_ROOT_PASSWORD"
        #  value: "1234"
        #- name: "MYSQL_DATABASE"
        #  value: "banco"
      #env: Exemplo de como carregar variaveis especificas de um configMap
      #  - name: MYSQL_ROOT_PASSWORD
      #    valueFrom:
      #      configMapKeyRef: #Pega o valor de um config map
      #        name: db-configmap #Nome do configMap onde esta o valor
      #        key: MYSQL_ROOT_PASSWORD #Chave de configMap que contem o valor
      envFrom: #Importa todos os valores do config Map
        - configMapRef:
            name: db-configmap