apiVersion: v1
kind: Service
metadata:
  name: svc-sistema-noticias
spec:
  type: NodePort
  ports:
    - port: 80 #É a porta por onde este servico podera ser acessado internamente no Cluster
      nodePort: 30001 #30000 - 32767 É a porta por onde este servico podera ser acessado externamente no Cluster
  selector:
    app: sistema-noticias


#Acessando esse NodePort externamente do Cluster na porta 30001 fará que com a requisição seja roteada para a porta 80 do Pod com label app=sistema-noticias