apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: portal-noticias-replicaset
spec:
  replicas: 0
  # Mesmo que o Pod seja definido junto com o ReplicaSet é necessário setar o selector para que este ReplicaSet gerencie
  # o Pod definido em 'template'
  selector: 
    matchLabels:
      app: portal-noticias
  template: #Informacoes de identificacao do Pod, como se tivesse definindo um Pod em um arquivo de Pod
    metadata: 
      name: portal-noticias
      labels:
        app: portal-noticias
    spec:
      containers:
        - name: portal-noticias-container
          image: aluracursos/portal-noticias:1
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: portal-configmap
