apiVersion: v1
kind: Pod
metadata:
  name: pod-volume  
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /volume-dentro-do-container
          name: primeiro-volume
    - name: nginx-stable
      image: nginx:stable
      volumeMounts:
        - mountPath: /volume-dentro-do-container
          name: primeiro-volume
  # Sao independentes de Container, mas dependentes de Pods, ou seja, se o Pod for excluído, o mapeamento do volume também será,  
  # mas os arquivos serão mantido, porém não estarão acessíveis por nenhum outro Pod a não ser que um novo mapeamento seja feito
  # Veja PersistentVolumeClaim para criar uma mapeamento independente de Pods
  volumes: 
    - name: primeiro-volume      
      hostPath: #Poderia ser persistentVolumeClaim
        path: /tmp/primeiro-volume
        # Colocando apenas Directory nao funcionou no Mac
        # Nao foi possivel encontrar onde que fica o diretorio gerado
        # por este comando no Mac
        # type: DirectoryOrCreate
