apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-deployment
spec:
  replicas: 1
  template: 
    metadata: 
      name: nginx-pod
      labels:
        app: nginx-pod
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80
  selector:
    matchLabels:
      app: nginx-pod

---

apiVersion: v1
kind: Service
metadata:
  name: svc-nginx
spec:
  ## O ClusterIP podera ser acessado internamente também por svc-nginx.default.svc onde default e o nome do namespace
  type: ClusterIP 
  ports:
    - port: 80
  selector:
    app: nginx-pod


# Pode ser testado com o CURL do proprio container do Nginx
# kubectl exec nome_pod -it  -- sh


---

apiVersion: v1
kind: Service
metadata:
  name: svc-nginx-nodeport
spec:
  ## O ClusterIP podera ser acessado internamente também por svc-nginx.default.svc onde default e o nome do namespace
  type: NodePort
  ports:
    - port: 80
      nodePort: 30000
  selector:
    app: nginx-pod