apiVersion: v1
kind: Pod
metadata:
  name: pod-volume  
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: /volume-dentro-do-container
          name: primeiro-volume
    - name: nginx-stable
      image: nginx:stable
      volumeMounts:
        - mountPath: /volume-dentro-do-container
          name: primeiro-volume
  volumes: #Sao independentes de Container, mas dependentes de Pods  
    - name: primeiro-volume
      hostPath:
        path: /tmp/primeiro-volume
        # Colocando apenas Directory nao funcionou no Mac
        # Nao foi possivel encontrar onde que fica o diretorio gerado
        # por este comando no Mac
        # type: DirectoryOrCreate
